// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetBreedList():Promise<Array<string>>;

export function GetImageUrlsByBreed(arg1:string):Promise<Array<string>>;

export function GetRandomImageUrl():Promise<string>;

export function Search(arg1:string,arg2:string,arg3:main.OptionsType):Promise<string>;

export function SelectFile():Promise<string>;

export function SelectFolder():Promise<string>;
